categories:
  1:
    name: "蛋糕"
    products:
      1:
        name: "草莓酸奶养颜蛋糕"
      2:
        name: "雪人茶曲"
      3:
        name: "抹抹清新"
      4:
        name: "相思抹茶"
      5:
        name: "情迷黑森林"
  2:
    name: "饮品"
    products:
      1:
        name: "摩卡"
      2:
        name: "美式咖啡"
      3:
        name: "绿茶多多"
  3:
    name: "面包"
    products:
      1:
        name: "山药号角"
      2:
        name: "麦麦轻芝士"
