products:
  1:
    category: "蛋糕"
    name: "草莓酸奶养颜蛋糕"
  2:
    category: "蛋糕"
    name: "雪人茶曲"
  3:
    category: "蛋糕"
    name: "抹抹清新"
  4:
    category: "蛋糕"
    name: "相思抹茶"
  5:
    category: "蛋糕"
    name: "情迷黑森林"
  7:
    category: "饮品"
    name: "摩卡"
  8:
    category: "饮品"
    name: "美式咖啡"
  9:
    category: "饮品"
    name: "绿茶多多"
  10:
    category: "面包"
    name: "山药号角"
  11:
    category: "面包"
    name: "麦麦轻芝士"
